
#' Classify indels into different types
#'
#' @param indels A indel list. Columns include: "Sample","chr", "position", "REF", "ALT"
#' @param genome.v : "hg19", "hg38"
#' @return Classified indel list
#' @export
indel_classifier89 <- function(indels, genome.v){
  #names(indels) <- c("Sample","chr", "position", "REF", "ALT")
  # indels$chr <- paste0("chr",indels$chr)

  # indel[indel$chr=="23","chr"]="X"
  # indel[indel$chr=="24","chr"]="Y"

  ## prepare indels
  prep_df <- prepare_indels(as.data.frame(indels),"pancan",genome.v)
  ## Segment indels
  s <- segment_indels(prep_df) #get('segment_indels',envir = .GlobalEnv)(prep_df$change,prep_df$slice3)

  s$mh_length <- s$indel.length-s$spacer_length
  s[s$mh_length>s$prime3_reps,"mh_length"] <- s[s$mh_length>s$prime3_reps,"prime3_reps"]

  ## Assign indels m5
  s_classified <- assign_channels_m5(s)

  return(s_classified)

}


#' Assign each indel a channel
#'
#' @param indel.df A classified indel list generated by function indel_classifier89()
#' @return An indel list with channel information
#' @export
assign_channels_m5 <- function(indel.df) {

  indel.df$type_4 <- NULL   # Level 2: medium v2
  indel.df$type_3 <- NULL   # Level 1: [+T]Rep=0; [+T]1<=Rep<=4; [+T]5<=Rep; [+C]Rep=0; [+C]1<=Rep<=4; [+C]5<=Rep;  [-T]Rep=1; [-T]2<=Rep<=4; [-T]5<=Rep; [-C]Rep=1; [-C]2<=Rep<=4; [-C]5<=Rep;
  indel.df$type_2 <- NULL   # For color: [+T]; [+C]; [-T]; [-C];
  indel.df$type_1 <- ""     # "+"; "-"; "Complex"
  indel.df$rep_level <- "-"
  indel.df[indel.df$indel.type=="I","type_1"] <- "+"
  indel.df[indel.df$indel.type=="D","type_1"] <- "-"
  indel.df[indel.df$indel.type=="DI","type_1"] <- "Complex"

  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps<2,"rep_level"] <- "NonRep"
  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps>1 & indel.df$prime3_reps<=4,"rep_level"] <- "ShortRep_leq4"
  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps>4,"rep_level"] <- "LongRep_g4"

  indel.df[indel.df$indel.type=="D" & indel.df$original_reps==1,"rep_level"] <- "NonRep"
  indel.df[indel.df$indel.type=="D" & indel.df$original_reps>1 & indel.df$original_reps<=4,"rep_level"] <- "ShortRep_leq4"
  indel.df[indel.df$indel.type=="D" & indel.df$original_reps>4,"rep_level"] <- "LongRep_g4"

  # Complex
  if(dim(indel.df[indel.df$indel.type=="DI",])[1]>0){
    indel.df[indel.df$indel.type=="DI","indel.length"] <- nchar(indel.df[indel.df$indel.type=="DI","REF"])
    indel.df[indel.df$indel.type=="DI","change"] <- indel.df[indel.df$indel.type=="DI","REF"]
   # indel.df[indel.df$indel.type=="DI","slice5"] <- as.character(getSeq(Hsapiens, indel.df[indel.df$indel.type=="DI","chr"], (indel.df[indel.df$indel.type=="DI","pos"]-50), (indel.df[indel.df$indel.type=="DI","pos"]-1)))
    # indel.df[indel.df$indel.type=="DI","slice3"] <- as.character(getSeq(Hsapiens, indel.df[indel.df$indel.type=="DI","chr"],(indel.df[indel.df$indel.type=="DI","pos"]+nchar(indel.df[indel.df$indel.type=="DI","REF"])), (indel.df[indel.df$indel.type=="DI","pos"]+nchar(indel.df[indel.df$indel.type=="DI","REF"])+49)))

  }


  # 5' base and 3' base before and after repeats for 1 base indels
  indel.df$rep_slice5 <- "-"
  indel.df$rep_slice3 <- "-"



  #indel.df[indel.df$indel.type=="DI","slice3"] <-

  indel.new <- NULL
  #[+C], [+T], [-C], [-T]

  #[+C], [+T] # 784448

  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length==1 & change_pyr %in% c("C","T"))
  if(dim(indel.b1)[1]>0){
    indel.b1$type_2 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]")
    indel.b1$type_3 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]",indel.b1$rep_level)

    if(dim(indel.b1[indel.b1$change %in% c("C","T"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice5 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr,nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr), nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr))
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice3_pyr, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1)
    }

    if(dim(indel.b1[indel.b1$change %in% c("G","A"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice5 <- stringr::str_sub(indel.b1[indel.b1$change %in% c("G","A"), ]$slice5_pyr,-(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1), -(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1))
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("G","A"), ]$slice3_pyr, 1, 1)
    }

    ## [+C]: A|[+C]Rep=0|A/T 16885
    indel.b2 <- subset(indel.b1, change_pyr=="C" & prime3_reps==0 & rep_slice5=="A" & rep_slice3%in% c("A","T"))
    if(dim(indel.b2)[1]>0){
      indel.b2$type_4 <- paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep=", indel.b2$prime3_reps, "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }

    ## other [+C]
    indel.b2 <- subset(indel.b1,change_pyr=="C" & !(prime3_reps==0 & rep_slice5=="A" & rep_slice3%in% c("A","T")) )
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4=""
      if(dim(indel.b2[indel.b2$prime3_reps<=3,])[1]>0){indel.b2[indel.b2$prime3_reps<=3,]$type_4 <-"[+C]Rep_leq3"}
      if(dim(indel.b2[indel.b2$prime3_reps%in%c(4,5,6),])[1]>0){indel.b2[indel.b2$prime3_reps%in%c(4,5,6),]$type_4 <-"[+C]Rep_456"}
      if(dim(indel.b2[indel.b2$prime3_reps%in%c(7,8,9),])[1]>0){indel.b2[indel.b2$prime3_reps%in%c(7,8,9),]$type_4 <-"[+C]Rep_789"}
      indel.new <- rbind(indel.new,indel.b2)
    }

    ##  A/C/G|[+T]Rep=1,2,3,4|A/C/G 92941
    indel.b2 <- subset(indel.b1,change_pyr=="T" & prime3_reps%in% c(0,1,2,3,4))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_leq4", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)

    }
    ##  A/C/G|[+T]Rep=5,6,7|A/C/G 342048
    indel.b2 <- subset(indel.b1,change_pyr=="T" & prime3_reps%in% c(5,6,7))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_567", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
    ##  A/C/G|[+T]Rep=8,9|A/C/G 252483
    indel.b2 <- subset(indel.b1,change_pyr=="T" & prime3_reps%in% c(8,9))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_89", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }

  }
  # + N-mer TR>=2 # 57208  spacer_length ==0: no spacer or spacer unavailable
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & prime3_reps >=2 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("Ins_nMer")
    indel.b1$type_3 <- paste0("Ins_nMer_",indel.b1$rep_level)
    indel.b1$type_4 <- paste0("Ins_nMer_","R",indel.b1$prime3_reps)
    if(dim(indel.b1[indel.b1$prime3_reps<=4,])[1]>0){indel.b1[indel.b1$prime3_reps<=4,"type_4"] <- paste0("Ins_nMer","_R234")}
    if(dim(indel.b1[indel.b1$prime3_reps>4,])[1]>0){indel.b1[indel.b1$prime3_reps>4,"type_4"] <- paste0("Ins_nMer","_R5")}
    indel.new <- rbind(indel.new,indel.b1)
  }

  # TR=1 & spacer_length==0
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & prime3_reps ==1 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R1"
    if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length>=5,"type_4"],"_L5")}
    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length<5,"type_4"],"_L234")}
    indel.new <- rbind(indel.new,indel.b1)
  }
  # + NonRep TR=0 & spacer_length==0 # spacer unavailable. the whole indel is spacer
  # Ins_NonRep_R0_L234
  # Ins_NonRep_R0_L5
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & (prime3_reps ==0 & spacer_length==0) )
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R0"
    if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length>=5,"type_4"],"_L5")}
    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length<5,"type_4"],"_L234")}
    indel.new <- rbind(indel.new,indel.b1)
  }
  # + NonRep TR=0 & spacer_length>0
  # Ins_NonRep_R0_L234
  # Ins_NonRep_R0_L5
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & spacer_length>0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R0"

    if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length>=5,"type_4"],"_L5")}
    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length<5,"type_4"],"_L234")}

    indel.new <- rbind(indel.new,indel.b1)
  }

  #[-C], [-T] # 1447209

  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length==1 & change_pyr %in% c("C","T"))
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]")
    indel.b1$type_3 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]",indel.b1$rep_level)

    if(dim(indel.b1[indel.b1$change %in% c("C","T"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice5 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr,nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr), nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr))
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice3_pyr, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1)

    }

    if(dim(indel.b1[indel.b1$change %in% c("G","A"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice5 <- stringr::str_sub(indel.b1[indel.b1$change %in% c("G","A"), ]$slice5_pyr,-(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1), -(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1))
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("G","A"), ]$slice3_pyr, 1, 1)

    }


    ## [-C]: [-C]Rep<=3|A/T 227287
    indel.b2 <- subset(indel.b1, change_pyr=="C" & original_reps<=3 & rep_slice3%in% c("A","T"))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("[",indel.b2$type_1,indel.b2$change_pyr,"]Rep=",indel.b2$original_reps, "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }

    ## [-C]: [-C]Rep_45|A/T 227287
    indel.b2 <- subset(indel.b1, change_pyr=="C" & original_reps%in%c(4,5) & rep_slice3%in% c("A","T"))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_45", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
    ## [-C]: [-C]Rep_leq5|G
    indel.b2 <- subset(indel.b1, change_pyr=="C" & original_reps<=5 & rep_slice3=="G")
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_leq5", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
    ##  [-C]Rep=6,7  39844
    indel.b2 <- subset(indel.b1,change_pyr=="C" & original_reps>=6 )
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0("[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_6")
      indel.new <- rbind(indel.new,indel.b2)
    }

    ##  A/C/G|[-T]Rep=1,2,3,4|A/C/G 51541
    indel.b2 <- subset(indel.b1,change_pyr=="T" & original_reps%in% c(1,2,3,4))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_leq4", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
    ##  A/C/G|[-T]Rep=5-7|A/C/G 517592
    indel.b2 <- subset(indel.b1,change_pyr=="T" & original_reps%in% c(5,6,7))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_567", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
    ##  A/C/G|[-T]Rep=8,9|A/C/G 550381
    indel.b2 <- subset(indel.b1,change_pyr=="T" & original_reps%in% c(8,9))
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"|[",indel.b2$type_1,indel.b2$change_pyr,"]Rep_89", "|",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }

  }
  # - N-mer  # 147452
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps >0 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("Del_nMer")
    indel.b1$type_3 <- paste0("Del_nMer_",indel.b1$rep_level)
    indel.b1$type_4 <- paste0("Del_nMer","_R",indel.b1$original_reps)
    if(dim(indel.b1[indel.b1$unit_length<=2 & indel.b1$original_reps<5,])[1]>0){indel.b1[indel.b1$unit_length<=2 & indel.b1$original_reps<5,"type_4"] <- paste0("Del_nMer_","U12_R234")}
    if(dim(indel.b1[indel.b1$unit_length<=2 & indel.b1$original_reps>=5,])[1]>0){indel.b1[indel.b1$unit_length<=2 & indel.b1$original_reps>=5,"type_4"] <- paste0("Del_nMer_","U12_R5")}
    if(dim(indel.b1[indel.b1$unit_length>2 & indel.b1$original_reps==2,])[1]>0){indel.b1[indel.b1$unit_length>2 & indel.b1$original_reps==2,"type_4"] <- paste0("Del_nMer_","U3_R2")}
    if(dim(indel.b1[indel.b1$unit_length>2 & indel.b1$original_reps>2,])[1]>0){indel.b1[indel.b1$unit_length>2 & indel.b1$original_reps>2,"type_4"] <- paste0("Del_nMer_","U3_R3")}
    indel.new <- rbind(indel.new,indel.b1)
  }
  # - Spaced # 12903
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps >0 & spacer_length>0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Del_Spaced"
    indel.b1$type_3 <- paste0("Del_Spaced_L",indel.b1$indel.length)
    if(dim(indel.b1[indel.b1$indel.length<=5,])[1]>0){indel.b1[indel.b1$indel.length<=5,"type_3"] <- "Del_Spaced_short_leq5"}
    if(dim(indel.b1[indel.b1$indel.length>5,])[1]>0){indel.b1[indel.b1$indel.length>5,"type_3"] <- "Del_Spaced_long_g5"}
    indel.b1$type_4 <- paste0(indel.b1$type_3,"_mh",indel.b1$mh_length)
    if(dim(indel.b1[indel.b1$indel.length<=5 & indel.b1$mh>=3,])[1]>0){indel.b1[indel.b1$indel.length<=5 & indel.b1$mh>=3,"type_4"] <- paste0(indel.b1[indel.b1$indel.length<=5 & indel.b1$mh>=3,"type_3"],"_mh3")}
    if(dim(indel.b1[indel.b1$indel.length>5 & indel.b1$mh>=4,])[1]>0){indel.b1[indel.b1$indel.length>5 & indel.b1$mh>=4,"type_4"] <- paste0(indel.b1[indel.b1$indel.length>5 & indel.b1$mh>=4,"type_3"],"_mh4")}
    indel.new <- rbind(indel.new,indel.b1)
  }

  # - NonRep TR=0 # 4413
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps == 0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Del_NonRep"
    indel.b1$type_3 <- "Del_NonRep"
    indel.b1$type_4 <- paste0("Del_NonRep_L",indel.b1$indel.length)
    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length<5,"type_3"],"_L234")}
    if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- paste0(indel.b1[indel.b1$indel.length>=5,"type_3"],"_L5")}
    indel.new <- rbind(indel.new,indel.b1)
  }
  # Complex # 11821
  if(dim(indel.df[indel.df$indel.type=="DI",])[1]>0){
    indel.b1 <- subset(indel.df,indel.type=="DI")
    indel.b1$type_2 <- "Complex"
    indel.b1$type_3 <- "Complex"
    indel.b1$type_4 <- "Complex"
    indel.new <- rbind(indel.new,indel.b1)
  }



  #a=data.frame(table(indel.new$VariantID))
  #a=a[order(a$Freq,decreasing=T),]
  return(indel.new)
} # 89 # removes single C/T indel in repeats >=10


