
#' expand 89 channels
#'
#' @param indels A indel list. Columns include: "Sample","chr", "position", "REF", "ALT"
#' @param genome.v : "hg19", "hg38"
#' @return Classified indel list
#' @export
indel_classifier_full <- function(indels, genome.v){


  ## prepare indels
  prep_df <- prepare_indels(as.data.frame(indels),"pancan",genome.v)
  ## Segment indels
  s <- segment_indels(prep_df) #get('segment_indels',envir = .GlobalEnv)(prep_df$change,prep_df$slice3)

  s$mh_length <- s$indel.length-s$spacer_length
  s$prime3_rep_length <- nchar(s$prime3_rep)
  s[s$mh_length>s$prime3_rep_length,"mh_length"] <- s[s$mh_length>s$prime3_rep_length,"prime3_rep_length"]

  ## Assign indels m5
  s_classified <- assign_channels_mf(s)

  return(s_classified)

}


#' Assign each indel a channel from 464 channels
#'
#' @param indel.df A classified indel list generated by function indel_classifier_full()
#' @return An indel list with channel information
#' @export
assign_channels_mf <- function(indel.df) {
  indel.df$type_4 <- NULL   # Level 2: 464 channels
  indel.df$type_3 <- NULL   # Level 1: [+T]Rep=0; [+T]1<=Rep<=4; [+T]5<=Rep; [+C]Rep=0; [+C]1<=Rep<=4; [+C]5<=Rep;  [-T]Rep=1; [-T]2<=Rep<=4; [-T]5<=Rep; [-C]Rep=1; [-C]2<=Rep<=4; [-C]5<=Rep;
  indel.df$type_2 <- NULL   # For color: [+T]; [+C]; [-T]; [-C];
  indel.df$type_1 <- ""     # "+"; "-"; "Complex"
  indel.df$rep_level <- "-"
  indel.df[indel.df$indel.type=="I","type_1"] <- "Ins"
  indel.df[indel.df$indel.type=="D","type_1"] <- "Del"
  indel.df[indel.df$indel.type=="DI","type_1"] <- "Complex"

  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps<2,"rep_level"] <- "NonRep"
  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps>1 & indel.df$prime3_reps<=4,"rep_level"] <- "ShortRep_leq4"
  indel.df[indel.df$indel.type=="I" & indel.df$prime3_reps>4,"rep_level"] <- "LongRep_g4"

  indel.df[indel.df$indel.type=="D" & indel.df$original_reps==1,"rep_level"] <- "NonRep"
  indel.df[indel.df$indel.type=="D" & indel.df$original_reps>1 & indel.df$original_reps<=4,"rep_level"] <- "ShortRep_leq4"
  indel.df[indel.df$indel.type=="D" & indel.df$original_reps>4,"rep_level"] <- "LongRep_g4"

  # Complex
  if(dim(indel.df[indel.df$indel.type=="DI",])[1]>0){
    indel.df[indel.df$indel.type=="DI","indel.length"] <- nchar(indel.df[indel.df$indel.type=="DI","REF"])
    indel.df[indel.df$indel.type=="DI","change"] <- indel.df[indel.df$indel.type=="DI","REF"]
    # indel.df[indel.df$indel.type=="DI","slice5"] <- as.character(getSeq(Hsapiens, indel.df[indel.df$indel.type=="DI","chr"], (indel.df[indel.df$indel.type=="DI","pos"]-50), (indel.df[indel.df$indel.type=="DI","pos"]-1)))
    # indel.df[indel.df$indel.type=="DI","slice3"] <- as.character(getSeq(Hsapiens, indel.df[indel.df$indel.type=="DI","chr"],(indel.df[indel.df$indel.type=="DI","pos"]+nchar(indel.df[indel.df$indel.type=="DI","REF"])), (indel.df[indel.df$indel.type=="DI","pos"]+nchar(indel.df[indel.df$indel.type=="DI","REF"])+49)))

  }


  # 5' base and 3' base before and after repeats for 1 base indels
  indel.df$rep_slice5 <- "-"
  indel.df$rep_slice3 <- "-"



  #indel.df[indel.df$indel.type=="DI","slice3"] <-

  indel.new <- NULL
  #[+C], [+T]
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length==1 & change_pyr %in% c("C","T"))
  if(dim(indel.b1)[1]>0){
    indel.b1$type_2 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]")
    indel.b1$type_3 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]",indel.b1$rep_level)

    if(dim(indel.b1[indel.b1$change %in% c("C","T"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice5 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr,nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr), nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr))
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice3_pyr, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1)
    }

    if(dim(indel.b1[indel.b1$change %in% c("G","A"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice5 <- stringr::str_sub(indel.b1[indel.b1$change %in% c("G","A"), ]$slice5_pyr,-(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1), -(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1))
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("G","A"), ]$slice3_pyr, 1, 1)
    }

    ## [+C]
    indel.b2 <- subset(indel.b1, change_pyr=="C")
    if(dim(indel.b2)[1]>0){
      indel.b2$type_4 <- paste0(indel.b2$rep_slice5,"[",indel.b2$type_1,"(",indel.b2$change_pyr,"):R", indel.b2$prime3_reps, "]",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }


    ##  [+T]
    indel.b2 <- subset(indel.b1,change_pyr=="T")
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <-paste0(indel.b2$rep_slice5,"[",indel.b2$type_1, "(",indel.b2$change_pyr,"):R",indel.b2$prime3_reps, "]",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)

    }

  }

  #[-C], [-T]

  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length==1 & change_pyr %in% c("C","T"))
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]")
    indel.b1$type_3 <- paste0("[",indel.b1$type_1,indel.b1$change_pyr,"]",indel.b1$rep_level)

    if(dim(indel.b1[indel.b1$change %in% c("C","T"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice5 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr,nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr), nchar(indel.b1[indel.b1$change %in% c("C","T"), ]$slice5_pyr))
      indel.b1[indel.b1$change %in% c("C","T"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("C","T"), ]$slice3_pyr, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1, indel.b1[indel.b1$change %in% c("C","T"), ]$prime3_reps+1)

    }

    if(dim(indel.b1[indel.b1$change %in% c("G","A"), ])[1]>0){
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice5 <- stringr::str_sub(indel.b1[indel.b1$change %in% c("G","A"), ]$slice5_pyr,-(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1), -(indel.b1[indel.b1$change %in% c("G","A"), ]$prime3_reps+1))
      indel.b1[indel.b1$change %in% c("G","A"), ]$rep_slice3 <- substr(indel.b1[indel.b1$change %in% c("G","A"), ]$slice3_pyr, 1, 1)

    }


    ## [-C]
    indel.b2 <- subset(indel.b1, change_pyr=="C")
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$rep_slice5,"[", indel.b2$type_1,"(",indel.b2$change_pyr,"):R",indel.b2$original_reps, "]",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }

    ##  [-T]
    indel.b2 <- subset(indel.b1,change_pyr=="T")
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$rep_slice5,"[", indel.b2$type_1,"(",indel.b2$change_pyr,"):R",indel.b2$original_reps, "]",indel.b2$rep_slice3)
      indel.new <- rbind(indel.new,indel.b2)
    }
  }

  # + N-mer TR>=2 # 57208  spacer_length ==0: no spacer or spacer unavailable   [Ins:L(2,):R(2,4)]  [Ins:L(2,):R(5,)]
  # + Ins(2,):R(0,9)
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & prime3_reps >=2 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("Ins_nMer")
    indel.b1$type_3 <- paste0("Ins_nMer_",indel.b1$rep_level)
    indel.b1$type_4 <- paste0("Ins_nMer_","R",indel.b1$prime3_reps)

    indel.b2 <- subset(indel.b1, indel.length<=4 & prime3_reps<=4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R",indel.b2$prime3_reps)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1,indel.length<=4 & prime3_reps>4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R(5,9)")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1,indel.length>4 & unit_length<3 & prime3_reps<=4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Ins(5,):U",indel.b2$unit_length,":R",indel.b2$prime3_reps)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>4 & unit_length>=3 & prime3_reps<=4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Ins(5,):U(3,)",":R",indel.b2$prime3_reps)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>4 & indel.b1$unit_length<3 & indel.b1$prime3_reps>4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Ins(5,):U",indel.b2$unit_length,":R(5,9)")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>4 & unit_length>=3 & prime3_reps>4)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Ins(5,):U(3,):R(5,9)")
      indel.new <- rbind(indel.new,indel.b2)

    }

    #if(dim(indel.b1[indel.b1$indel.length<=4 & indel.b1$prime3_reps<=4,])[1]>0){indel.b1[indel.b1$indel.length<=4 & indel.b1$prime3_reps<=4,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R",indel.b1$prime3_reps)}
    #if(dim(indel.b1[indel.b1$indel.length<=4 & indel.b1$prime3_reps>4,])[1]>0){indel.b1[indel.b1$indel.length<=4 & indel.b1$prime3_reps>4,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R(5,9)")}

    #if(dim(indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length<3 & indel.b1$prime3_reps<=4,])[1]>0){indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length<3 & indel.b1$prime3_reps<=4,"type_4"] <- paste0("Ins(5,):U",indel.b1$unit_length,":R",indel.b1$prime3_reps)}
    #if(dim(indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length>3 & indel.b1$prime3_reps<=4,])[1]>0){indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length>3 & indel.b1$prime3_reps<=4,"type_4"] <- paste0("Ins(5,):U(3,)",":R",indel.b1$prime3_reps)}
    #if(dim(indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length<3 & indel.b1$prime3_reps>4,])[1]>0){indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length<3 & indel.b1$prime3_reps>4,"type_4"] <- paste0("Ins(5,):U",indel.b1$unit_length,":R(5,9)")}
    #if(dim(indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length>3 & indel.b1$prime3_reps>4,])[1]>0){indel.b1[indel.b1$indel.length>4 & indel.b1$unit_length>=3 & indel.b1$prime3_reps>4,"type_4"] <- paste0("Ins(5,):U(3,):R(5,9)")}
  }

  # TR=1 & spacer_length==0  [Ins:L(2,4):R1] [Ins:L(5,):R1]
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & prime3_reps ==1 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R1"

    indel.b2 <- subset(indel.b1, indel.length>=5 & unit_length>=3)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Ins(5,):U(3,):R1"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>=5 & unit_length<3)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Ins(5,):U",indel.b2$unit_length,":R1")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R1")
      indel.new <- rbind(indel.new,indel.b2)

    }

    #if(dim(indel.b1[indel.b1$indel.length>=5 & indel.b1$unit_length>=3,])[1]>0){indel.b1[indel.b1$indel.length>=5 & indel.b1$unit_length>=3,"type_4"] <- "Ins(5,):U(3,):R1"}
    #if(dim(indel.b1[indel.b1$indel.length>=5 & indel.b1$unit_length<3,])[1]>0){indel.b1[indel.b1$indel.length>=5 & indel.b1$unit_length<3,"type_4"] <- paste0("Ins(5,):U",indel.b1$unit_length,":R1")}
    #if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <-  paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R1")}
  }
  # + NonRep TR=0 & spacer_length==0 # spacer unavailable. the whole indel is spacer [Ins:L(2,4):R0] [Ins:L(5,):R0]
  # Ins_NonRep_R0_L234
  # Ins_NonRep_R0_L5
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & (prime3_reps ==0 & spacer_length==0) )
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R0"

    indel.b2 <- subset(indel.b1,indel.length>=5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Ins(5,):R0"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R0")
      indel.new <- rbind(indel.new,indel.b2)

    }
 #   if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- "Ins(5,):U(5,):R0"}
#    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R0")}
  }


  # + NonRep TR=0 & spacer_length>0
  # Ins_NonRep_R0_L234
  # Ins_NonRep_R0_L5
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & spacer_length>0 & prime3_reps ==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R0"

    indel.b2 <- subset(indel.b1, indel.length>=5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Ins(5,):R0"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$indel.length,":R0")
      indel.new <- rbind(indel.new,indel.b2)

    }


  #  if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- "Ins(5,):U(5,):R0"}
   # if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$indel.length,":R0")}

  }



  # + NonRep TR>0 & spacer_length>0
  # Ins_NonRep_R0_L234
  # Ins_NonRep_R0_L5
  indel.b1 <- subset(indel.df,indel.type=="I" & indel.length>1 & spacer_length>0 & prime3_reps >0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Ins_NonRep"
    indel.b1$type_3 <- "Ins_NonRep"
    indel.b1$type_4 <- "Ins_NonRep_R0"

    indel.b2 <- subset(indel.b1, indel.length>=5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Ins(5,):M"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Ins(2,4):M"
      indel.new <- rbind(indel.new,indel.b2)

    }

#    if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- "Ins(5,):M"}
#    if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- "Ins(2,4):M"}

  }

   # - N-mer  # 147452   [Del:L(2,):U(1,2):R(2,4)]  [Del:L(2,):U(1,2):R(5,)]  [Del:L(2,):U(3,):R2] [Del:L(3,):U(3,):R(3,)]
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps >0 & spacer_length==0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- paste0("Del_nMer")
    indel.b1$type_3 <- paste0("Del_nMer_",indel.b1$rep_level)
    indel.b1$type_4 <- paste0("Del_nMer","_R",indel.b1$original_reps)

    indel.b2 <- subset(indel.b1, indel.length<=5 & indel.b1$original_reps<5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R",indel.b2$original_reps)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<=5 & indel.b1$original_reps>=5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length,":U",indel.b2$unit_length,":R(5,9)")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>5 & indel.b1$unit_length==1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(6,):U1:R(7,9)"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>5 & indel.b1$unit_length==2)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(6,):U2:R(4,9)"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>5 & indel.b1$unit_length==3)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(6,):U3:R(3,9)"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>5 & indel.b1$unit_length>3)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(6,):U(4,):R(2,9)"
      indel.new <- rbind(indel.new,indel.b2)

    }
#    if(dim(indel.b1[indel.b1$indel.length<=9 & indel.b1$original_reps<5,])[1]>0){indel.b1[indel.b1$indel.length<=9 & indel.b1$original_reps<5,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R",indel.b1$original_reps)}
#    if(dim(indel.b1[indel.b1$indel.length<=9 & indel.b1$original_reps>=5,])[1]>0){indel.b1[indel.b1$indel.length<=9 & indel.b1$original_rep>=5,"type_4"] <- paste0(indel.b1$type_1,indel.b1$indel.length,":U",indel.b1$unit_length,":R(5,9)")}

#    if(dim(indel.b1[indel.b1$indel.length>9,])[1]>0){indel.b1[indel.b1$indel.length<=9,"type_4"] <- "Del(10,):R(0,9)"}
  }



  # - Spaced # 12903  [Del:L(,5):M1] [Del:L(,5):M2]  [Del:L(,5):M(3,4)]  [Del:L(6,):M1]  [Del:L(6,):M2]  [Del:L(6,):M3]  [Del:L(6,):M(4,)]
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps >0 & spacer_length>0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Del_Spaced"
    indel.b1$type_3 <- paste0("Del_Spaced_L",indel.b1$indel.length)
    if(dim(indel.b1[indel.b1$indel.length<=5,])[1]>0){indel.b1[indel.b1$indel.length<=5,"type_3"] <- "Del_Spaced_short_leq5"}
    if(dim(indel.b1[indel.b1$indel.length>5,])[1]>0){indel.b1[indel.b1$indel.length>5,"type_3"] <- "Del_Spaced_long_g5"}

    indel.b2 <- subset(indel.b1, indel.length<=6)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length, ":M",indel.b2$mh_length)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>6 & mh_length<6)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0("Del(7,):M",indel.b2$mh_length)
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>6 & mh_length>=6)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(7,):M(6,)"
      indel.new <- rbind(indel.new,indel.b2)

    }


  }

  # - NonRep TR=0 # 4413      [Del:L(2,4):R1]  [Del:L(5,):R1]
  indel.b1 <- subset(indel.df,indel.type=="D" & indel.length>1 & prime3_reps == 0)
  if(dim(indel.b1)[1]>0){

    indel.b1$type_2 <- "Del_NonRep"
    indel.b1$type_3 <- "Del_NonRep"

    indel.b2 <- subset(indel.b1, indel.length<10 & unit_length==1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length, ":U1:R1")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>=10 & unit_length==1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(10,):U1:R1"
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length<10 & unit_length>1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- paste0(indel.b2$type_1,indel.b2$indel.length, ":U(2,):R1")
      indel.new <- rbind(indel.new,indel.b2)

    }

    indel.b2 <- subset(indel.b1, indel.length>=10 & unit_length>1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Del(10,):U(2,):R1"
      indel.new <- rbind(indel.new,indel.b2)

    }

   # if(dim(indel.b1[indel.b1$indel.length<5,])[1]>0){indel.b1[indel.b1$indel.length<5,"type_4"] <- "Del(2,4):R1"}
   # if(dim(indel.b1[indel.b1$indel.length>=5,])[1]>0){indel.b1[indel.b1$indel.length>=5,"type_4"] <- "Del(5,):R1"}
  }
  # Complex # 11821
  if(dim(indel.df[indel.df$indel.type=="DI",])[1]>0){
    indel.b1 <- subset(indel.df,indel.type=="DI")
    indel.b1$type_2 <- "Complex"
    indel.b1$type_3 <- "Complex"

    indel.b2 <- subset(indel.b1, nchar(REF)-nchar(ALT)==1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Complex(0,1)"
      indel.new <- rbind(indel.new,indel.b2)
    }

    indel.b2 <- subset(indel.b1, (nchar(REF)-nchar(ALT))<=5 & (nchar(REF)-nchar(ALT))>1)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Complex(2,5)"
      indel.new <- rbind(indel.new,indel.b2)
    }

    indel.b2 <- subset(indel.b1, (nchar(REF)-nchar(ALT))<=10 & (nchar(REF)-nchar(ALT))>5)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Complex(6,10)"
      indel.new <- rbind(indel.new,indel.b2)
    }

    indel.b2 <- subset(indel.b1, (nchar(REF)-nchar(ALT))<=20 & (nchar(REF)-nchar(ALT))>10)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Complex(11,20)"
      indel.new <- rbind(indel.new,indel.b2)
    }

    indel.b2 <- subset(indel.b1,  (nchar(REF)-nchar(ALT))>20)
    if(dim(indel.b2)[1]>0){

      indel.b2$type_4 <- "Complex(21,)"
      indel.new <- rbind(indel.new,indel.b2)
    }

  #  indel.b1$type_4 <- "Complex"
  #  indel.new <- rbind(indel.new,indel.b1)
  }



  #a=data.frame(table(indel.new$VariantID))
  #a=a[order(a$Freq,decreasing=T),]
  return(indel.new)
} #


