# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' segmentation function
#'
#' @param string A string
#' @param context Context of a string
#' @export
segment <- function(string, context) {
    .Call(`_indelsig_tools_lib_segment`, string, context)
}

